name: html-preview
on: [status]


jobs:
  html-preview:
    runs-on: ubuntu-latest
    name: html-preview
    steps:
      - uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/html/index.html
          circleci-jobs: html_demo
